baseURL = "https://sleepylee02.github.io/"
languageCode = "en-us"
title = "Jaeyoung Lee"
theme = "terminal"

[params]
  contentTypeName = "posts"
  themeColor = "orange" 
  showFullContent = false
  readingTime = true
  centerTheme = true

  [params.logo]
    logoText = "JAEYOUNG LEE"
    logoHomeLink = "/"

  [params.home]
    title = "JAEYOUNG LEE"
    subtitle = "Applied Statistics & Computer Science @ Yonsei Univ. \n Bridging Data Science with System Architecture."

  # Professional Menu Labels
  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 1
  [[menu.main]]
    identifier = "projects"
    name = "projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    identifier = "research"
    name = "research"
    url = "/research/"
    weight = 3
  [[menu.main]]
    identifier = "timeline"
    name = "timeline"
    url = "/timeline/"
    weight = 4
  [[menu.main]]
    identifier = "contact"
    name = "contact"
    url = "/contact/"
    weight = 5
